/*
 * Copyright © 2024 Rémi Denis-Courmont.
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#define VILL -0x8000

        .data
ff_vtype_e8:
ff_vtype_e8_1:
        .half   VILL
ff_vtype_e8_2:
        .half   VILL
ff_vtype_e8_4:
        .half   VILL
ff_vtype_e8_8:
        .half   VILL
ff_vtype_e8_16:
        .half   VILL
ff_vtype_e8_32:
        .half   VILL

ff_vtype_e16:
ff_vtype_e16_1:
        .half   VILL
ff_vtype_e16_2:
        .half   VILL
ff_vtype_e16_4:
        .half   VILL
ff_vtype_e16_8:
        .half   VILL
ff_vtype_e16_16:
        .half   VILL
