NAME = swscale

HEADERS = swscale.h                                                     \
          version.h                                                     \

OBJS = input.o                                                          \
       options.o                                                        \
       output.o                                                         \
       rgb2rgb.o                                                        \
       swscale.o                                                        \
       swscale_unscaled.o                                               \
       utils.o                                                          \
       yuv2rgb.o                                                        \

TESTPROGS = colorspace                                                  \
            swscale                                                     \
