OBJS-$(CONFIG_GRADFUN_FILTER)                += x86/vf_gradfun_init.o
OBJS-$(CONFIG_HQDN3D_FILTER)                 += x86/vf_hqdn3d_init.o
OBJS-$(CONFIG_INTERLACE_FILTER)              += x86/vf_interlace_init.o
OBJS-$(CONFIG_VOLUME_FILTER)                 += x86/af_volume_init.o
OBJS-$(CONFIG_YADIF_FILTER)                  += x86/vf_yadif_init.o

YASM-OBJS-$(CONFIG_GRADFUN_FILTER)           += x86/vf_gradfun.o
YASM-OBJS-$(CONFIG_HQDN3D_FILTER)            += x86/vf_hqdn3d.o
YASM-OBJS-$(CONFIG_INTERLACE_FILTER)         += x86/vf_interlace.o
YASM-OBJS-$(CONFIG_VOLUME_FILTER)            += x86/af_volume.o
YASM-OBJS-$(CONFIG_YADIF_FILTER)             += x86/vf_yadif.o
