DEF(200, RTSP_STATUS_OK, "OK")
DEF(405, RTSP_STATUS_METHOD, "Method Not Allowed")
DEF(453, RTSP_STATUS_BANDWIDTH, "Not Enough Bandwidth")
DEF(454, RTSP_STATUS_SESSION, "Session Not Found")
DEF(455, RTSP_STATUS_STATE, "Method Not Valid in This State")
DEF(459, RTSP_STATUS_AGGREGATE, "Aggregate operation not allowed")
DEF(460, RTSP_STATUS_ONLY_AGGREGATE, "Only aggregate operation allowed")
DEF(461, RTSP_STATUS_TRANSPORT, "Unsupported transport")
DEF(500, RTSP_STATUS_INTERNAL, "Internal Server Error")
DEF(503, RTSP_STATUS_SERVICE, "Service Unavailable")
DEF(505, RTSP_STATUS_VERSION, "RTSP Version not supported")
