clean::
	$(RM) $(CLEANSUFFIXES:%=libavcodec/vvc/%)

OBJS-$(CONFIG_VVC_DECODER)          +=  vvc/dec.o           \
                                        vvc/dsp.o           \
                                        vvc/cabac.o         \
                                        vvc/ctu.o           \
                                        vvc/data.o          \
                                        vvc/filter.o        \
                                        vvc/inter.o         \
                                        vvc/intra.o         \
                                        vvc/intra_utils.o   \
                                        vvc/itx_1d.o        \
                                        vvc/mvs.o           \
                                        vvc/ps.o            \
                                        vvc/refs.o          \
                                        vvc/thread.o        \
