clean::
	$(RM) $(CLEANSUFFIXES:%=libavcodec/vvc/%)

OBJS-$(CONFIG_VVC_DECODER)          +=  vvc/vvcdec.o            \
                                        vvc/vvcdsp.o            \
                                        vvc/vvc_cabac.o         \
                                        vvc/vvc_ctu.o           \
                                        vvc/vvc_data.o          \
                                        vvc/vvc_filter.o        \
                                        vvc/vvc_inter.o         \
                                        vvc/vvc_intra.o         \
                                        vvc/vvc_intra_utils.o   \
                                        vvc/vvc_itx_1d.o        \
                                        vvc/vvc_mvs.o           \
                                        vvc/vvc_ps.o            \
                                        vvc/vvc_refs.o          \
                                        vvc/vvc_thread.o        \
