FATE_TESTS += fate-4xm
fate-4xm: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/4xm/TimeGatep01s01n01a02_2.4xm -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-8bps
fate-8bps: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/8bps/full9iron-partial.mov -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-aac-demux
fate-aac-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/aac/ct_faac-adts.aac -acodec copy -f crc -
FATE_TESTS += fate-aasc
fate-aasc: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/aasc/AASC-1.5MB.AVI -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-adpcm-ea-r2
fate-adpcm-ea-r2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-mpc/THX_logo.mpc -vn -f crc -
FATE_TESTS += fate-adpcm-ea-r3
fate-adpcm-ea-r3: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-vp6/THX_logo.vp6 -vn -f crc -
FATE_TESTS += fate-aea-demux
fate-aea-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/aea/chirp.aea -acodec copy -f crc -
FATE_TESTS += fate-alg-mm
fate-alg-mm: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/alg-mm/ibmlogo.mm -an -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-amv
fate-amv: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/amv/MTV_high_res_320x240_sample_Penguin_Joke_MTV_from_WMV.amv -t 10 -f framecrc -
FATE_TESTS += fate-armovie-escape124
fate-armovie-escape124: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/rpl/ESCAPE.RPL -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-auravision
fate-auravision: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/auravision/SOUVIDEO.AVI -an -f framecrc -
FATE_TESTS += fate-auravision-v2
fate-auravision-v2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/auravision/salma-hayek-in-ugly-betty-partial-avi -an -f framecrc -
FATE_TESTS += fate-bethsoft-vid
fate-bethsoft-vid: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/bethsoft-vid/ANIM0001.VID -vsync 0 -t 5 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-bfi
fate-bfi: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/bfi/2287.bfi -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-bink-demux
fate-bink-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/bink/Snd0a7d9b58.dee -vn -acodec copy -f crc -
FATE_TESTS += fate-bink-demux-video
fate-bink-demux-video: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/bink/hol2br.bik -f framecrc -
FATE_TESTS += fate-caf
fate-caf: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/caf/caf-pcm16.caf -f crc -
FATE_TESTS += fate-cdgraphics
fate-cdgraphics: CMD = $$BUILD_PATH/ffmpeg -t 1 -i $$SAMPLES_PATH/cdgraphics/BrotherJohn.cdg -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-cljr
fate-cljr: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cljr/testcljr-partial.avi -f framecrc -
FATE_TESTS += fate-corepng
fate-corepng: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/png1/corepng-partial.avi -f framecrc -
FATE_TESTS += fate-creative-adpcm
fate-creative-adpcm: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/creative/intro-partial.wav -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-creative-adpcm-8-2.6bit
fate-creative-adpcm-8-2.6bit: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/creative/BBC_3BIT.VOC -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-creative-adpcm-8-2bit
fate-creative-adpcm-8-2bit: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/creative/BBC_2BIT.VOC -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-creative-adpcm-8-4bit
fate-creative-adpcm-8-4bit: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/creative/BBC_4BIT.VOC -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-creatureshock-avs
fate-creatureshock-avs: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/creatureshock-avs/OUTATIME.AVS -pix_fmt rgb24  -f framecrc -
FATE_TESTS += fate-cryo-apc
fate-cryo-apc: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cryo-apc/cine007.APC -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-cscd
fate-cscd: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/CSCD/sample_video.avi -an -vsync 0 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-cvid
fate-cvid: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cvid/laracroft-cinepak-partial.avi -an -f framecrc -
FATE_TESTS += fate-cvid-palette
fate-cvid-palette: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cvid/catfight-cvid-pal8-partial.mov -pix_fmt rgb24 -an -f framecrc -
FATE_TESTS += fate-cyberia-c93
fate-cyberia-c93: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cyberia-c93/intro1.c93 -t 3 -pix_fmt rgb24  -f framecrc -
FATE_TESTS += fate-cyuv
fate-cyuv: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cyuv/cyuv.avi -f framecrc -
FATE_TESTS += fate-d-cinema-demux
fate-d-cinema-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/d-cinema/THX_Science_FLT_1920-partial.302 -acodec copy -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-delphine-cin
fate-delphine-cin: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/delphine-cin/LOGO-partial.CIN -pix_fmt rgb24 -vsync 0 -f framecrc -
FATE_TESTS += fate-deluxepaint-anm
fate-deluxepaint-anm: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/deluxepaint-anm/INTRO1.ANM -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-dpx
fate-dpx: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/dpx/lighthouse_rgb48.dpx -f framecrc -
FATE_TESTS += fate-duck-dk3
fate-duck-dk3: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/duck/sop-audio-only.avi -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-duck-dk4
fate-duck-dk4: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/duck/salsa-audio-only.avi -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-duck-tm2
fate-duck-tm2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/duck/tm20.avi -f framecrc -
FATE_TESTS += fate-ea-cdata
fate-ea-cdata: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-cdata/166b084d.46410f77.0009b440.24be960c.cdata -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-ea-cmv
fate-ea-cmv: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-cmv/TITLE.CMV -vsync 0 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-ea-dct
fate-ea-dct: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/ea-dct/NFS2Esprit-partial.dct -f framecrc -
FATE_TESTS += fate-ea-mad-adpcm-ea-r1
fate-ea-mad-adpcm-ea-r1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-mad/NFS6LogoE.mad -f framecrc -
FATE_TESTS += fate-ea-mad-pcm-planar
fate-ea-mad-pcm-planar: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-mad/xeasport.mad -f framecrc -
FATE_TESTS += fate-ea-tgq
fate-ea-tgq: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-tgq/v27.tgq -an -f framecrc -
FATE_TESTS += fate-ea-tgv-ima-ea-eacs
fate-ea-tgv-ima-ea-eacs: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-tgv/INTRO8K-partial.TGV -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-ea-tgv-ima-ea-sead
fate-ea-tgv-ima-ea-sead: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-tgv/INTEL_S.TGV -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-ea-tqi-adpcm
fate-ea-tqi-adpcm: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-wve/networkBackbone-partial.wve -f framecrc -
FATE_TESTS += fate-ea-vp60
fate-ea-vp60: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-vp6/g36.vp6 -f framecrc -
FATE_TESTS += fate-ea-vp61
fate-ea-vp61: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ea-vp6/MovieSkirmishGondor.vp6 -t 4 -f framecrc -
FATE_TESTS += fate-feeble-dxa
fate-feeble-dxa: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/dxa/meetsquid.dxa -t 2 -pix_fmt rgb24  -f framecrc -
FATE_TESTS += fate-film-cvid-pcm-stereo-8bit
fate-film-cvid-pcm-stereo-8bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/film/logo-capcom.cpk -f framecrc -
FATE_TESTS += fate-flic-af11-palette-change
fate-flic-af11-palette-change: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fli/fli-engines.fli -t 3.3 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-flic-af12
fate-flic-af12: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fli/jj00c2.fli -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-flic-magiccarpet
fate-flic-magiccarpet: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fli/intel.dat -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-fraps-v0
fate-fraps-v0: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fraps/Griffin_Ragdoll01-partial.avi -f framecrc -
FATE_TESTS += fate-fraps-v1
fate-fraps-v1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fraps/sample-v1.avi -an -f framecrc -
FATE_TESTS += fate-fraps-v2
fate-fraps-v2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fraps/test3-nosound-partial.avi -f framecrc -
FATE_TESTS += fate-fraps-v3
fate-fraps-v3: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fraps/psclient-partial.avi -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-fraps-v4
fate-fraps-v4: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fraps/WoW_2006-11-03_14-58-17-19-nosound-partial.avi -f framecrc -
FATE_TESTS += fate-fraps-v5
fate-fraps-v5: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/fraps/fraps-v5-bouncing-balls-partial.avi -f framecrc -
FATE_TESTS += fate-frwu
fate-frwu: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/frwu/frwu.avi -f framecrc -
FATE_TESTS += fate-funcom-iss
fate-funcom-iss: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/funcom-iss/0004010100.iss -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-h264-conformance-aud_mw_e
fate-h264-conformance-aud_mw_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/AUD_MW_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-ba1_ft_c
fate-h264-conformance-ba1_ft_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BA1_FT_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-ba1_sony_d
fate-h264-conformance-ba1_sony_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BA1_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-ba2_sony_f
fate-h264-conformance-ba2_sony_f: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BA2_Sony_F.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-ba3_sva_c
fate-h264-conformance-ba3_sva_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/BA3_SVA_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-ba_mw_d
fate-h264-conformance-ba_mw_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BA_MW_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-bamq1_jvc_c
fate-h264-conformance-bamq1_jvc_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BAMQ1_JVC_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-bamq2_jvc_c
fate-h264-conformance-bamq2_jvc_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BAMQ2_JVC_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-banm_mw_d
fate-h264-conformance-banm_mw_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BANM_MW_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-basqp1_sony_c
fate-h264-conformance-basqp1_sony_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/BASQP1_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-caba1_sony_d
fate-h264-conformance-caba1_sony_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CABA1_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-caba1_sva_b
fate-h264-conformance-caba1_sva_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CABA1_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-caba2_sony_e
fate-h264-conformance-caba2_sony_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CABA2_Sony_E.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-caba2_sva_b
fate-h264-conformance-caba2_sva_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CABA2_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-caba3_sony_c
fate-h264-conformance-caba3_sony_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CABA3_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-caba3_sva_b
fate-h264-conformance-caba3_sva_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CABA3_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-caba3_toshiba_e
fate-h264-conformance-caba3_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CABA3_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cabac_mot_fld0_full
fate-h264-conformance-cabac_mot_fld0_full: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/camp_mot_fld0_full.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cabac_mot_frm0_full
fate-h264-conformance-cabac_mot_frm0_full: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/camp_mot_frm0_full.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cabac_mot_mbaff0_full
fate-h264-conformance-cabac_mot_mbaff0_full: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/camp_mot_mbaff0_full.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cabac_mot_picaff0_full
fate-h264-conformance-cabac_mot_picaff0_full: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/camp_mot_picaff0_full.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cabaci3_sony_b
fate-h264-conformance-cabaci3_sony_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CABACI3_Sony_B.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cabast3_sony_e
fate-h264-conformance-cabast3_sony_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CABAST3_Sony_E.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cabastbr3_sony_b
fate-h264-conformance-cabastbr3_sony_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CABASTBR3_Sony_B.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cabref3_sand_d
fate-h264-conformance-cabref3_sand_d: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CABREF3_Sand_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cacqp3_sony_d
fate-h264-conformance-cacqp3_sony_d: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CACQP3_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cafi1_sva_c
fate-h264-conformance-cafi1_sva_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAFI1_SVA_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cama1_sony_c
fate-h264-conformance-cama1_sony_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CAMA1_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cama1_toshiba_b
fate-h264-conformance-cama1_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMA1_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cama1_vtc_c
fate-h264-conformance-cama1_vtc_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/cama1_vtc_c.avc -f framecrc -
FATE_TESTS += fate-h264-conformance-cama2_vtc_b
fate-h264-conformance-cama2_vtc_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -i $$SAMPLES_PATH/h264-conformance/cama2_vtc_b.avc -f framecrc -
FATE_TESTS += fate-h264-conformance-cama3_sand_e
fate-h264-conformance-cama3_sand_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMA3_Sand_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cama3_vtc_b
fate-h264-conformance-cama3_vtc_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/cama3_vtc_b.avc -f framecrc -
FATE_TESTS += fate-h264-conformance-camaci3_sony_c
fate-h264-conformance-camaci3_sony_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMACI3_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-camanl1_toshiba_b
fate-h264-conformance-camanl1_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMANL1_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-camanl2_toshiba_b
fate-h264-conformance-camanl2_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMANL2_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-camanl3_sand_e
fate-h264-conformance-camanl3_sand_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMANL3_Sand_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-camasl3_sony_b
fate-h264-conformance-camasl3_sony_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMASL3_Sony_B.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-camp_mot_mbaff_l30
fate-h264-conformance-camp_mot_mbaff_l30: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMP_MOT_MBAFF_L30.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-camp_mot_mbaff_l31
fate-h264-conformance-camp_mot_mbaff_l31: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAMP_MOT_MBAFF_L31.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-canl1_sony_e
fate-h264-conformance-canl1_sony_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL1_Sony_E.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-canl1_sva_b
fate-h264-conformance-canl1_sva_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL1_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-canl1_toshiba_g
fate-h264-conformance-canl1_toshiba_g: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL1_TOSHIBA_G.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-canl2_sony_e
fate-h264-conformance-canl2_sony_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL2_Sony_E.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-canl2_sva_b
fate-h264-conformance-canl2_sva_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL2_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-canl3_sony_c
fate-h264-conformance-canl3_sony_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CANL3_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-canl3_sva_b
fate-h264-conformance-canl3_sva_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL3_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-canl4_sva_b
fate-h264-conformance-canl4_sva_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANL4_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-canlma2_sony_c
fate-h264-conformance-canlma2_sony_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANLMA2_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-canlma3_sony_c
fate-h264-conformance-canlma3_sony_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CANLMA3_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-capa1_toshiba_b
fate-h264-conformance-capa1_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAPA1_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-capama3_sand_f
fate-h264-conformance-capama3_sand_f: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAPAMA3_Sand_F.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-capcm1_sand_e
fate-h264-conformance-capcm1_sand_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CAPCM1_Sand_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-capcmnl1_sand_e
fate-h264-conformance-capcmnl1_sand_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CAPCMNL1_Sand_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-capm3_sony_d
fate-h264-conformance-capm3_sony_d: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAPM3_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-caqp1_sony_b
fate-h264-conformance-caqp1_sony_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CAQP1_Sony_B.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cavlc_mot_fld0_full_b
fate-h264-conformance-cavlc_mot_fld0_full_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/cvmp_mot_fld0_full_B.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cavlc_mot_frm0_full_b
fate-h264-conformance-cavlc_mot_frm0_full_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/cvmp_mot_frm0_full_B.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cavlc_mot_mbaff0_full_b
fate-h264-conformance-cavlc_mot_mbaff0_full_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/cvmp_mot_mbaff0_full_B.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cavlc_mot_picaff0_full_b
fate-h264-conformance-cavlc_mot_picaff0_full_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/cvmp_mot_picaff0_full_B.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cawp1_toshiba_e
fate-h264-conformance-cawp1_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CAWP1_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cawp5_toshiba_e
fate-h264-conformance-cawp5_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CAWP5_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-ci1_ft_b
fate-h264-conformance-ci1_ft_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CI1_FT_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-ci_mw_d
fate-h264-conformance-ci_mw_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CI_MW_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvbs3_sony_c
fate-h264-conformance-cvbs3_sony_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVBS3_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvcanlma2_sony_c
fate-h264-conformance-cvcanlma2_sony_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CVCANLMA2_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvfi1_sony_d
fate-h264-conformance-cvfi1_sony_d: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVFI1_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvfi1_sva_c
fate-h264-conformance-cvfi1_sva_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVFI1_SVA_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvfi2_sony_h
fate-h264-conformance-cvfi2_sony_h: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVFI2_Sony_H.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvfi2_sva_c
fate-h264-conformance-cvfi2_sva_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVFI2_SVA_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvma1_sony_d
fate-h264-conformance-cvma1_sony_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CVMA1_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvma1_toshiba_b
fate-h264-conformance-cvma1_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMA1_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmanl1_toshiba_b
fate-h264-conformance-cvmanl1_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMANL1_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmanl2_toshiba_b
fate-h264-conformance-cvmanl2_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMANL2_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmapaqp3_sony_e
fate-h264-conformance-cvmapaqp3_sony_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMAPAQP3_Sony_E.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmaqp2_sony_g
fate-h264-conformance-cvmaqp2_sony_g: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMAQP2_Sony_G.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmaqp3_sony_d
fate-h264-conformance-cvmaqp3_sony_d: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMAQP3_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmp_mot_fld_l30_b
fate-h264-conformance-cvmp_mot_fld_l30_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMP_MOT_FLD_L30_B.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cvmp_mot_frm_l31_b
fate-h264-conformance-cvmp_mot_frm_l31_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVMP_MOT_FRM_L31_B.26l -f framecrc -
FATE_TESTS += fate-h264-conformance-cvnlfi1_sony_c
fate-h264-conformance-cvnlfi1_sony_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -i $$SAMPLES_PATH/h264-conformance/CVNLFI1_Sony_C.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvnlfi2_sony_h
fate-h264-conformance-cvnlfi2_sony_h: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVNLFI2_Sony_H.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-cvpa1_toshiba_b
fate-h264-conformance-cvpa1_toshiba_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVPA1_TOSHIBA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvpcmnl1_sva_c
fate-h264-conformance-cvpcmnl1_sva_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CVPCMNL1_SVA_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvpcmnl2_sva_c
fate-h264-conformance-cvpcmnl2_sva_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CVPCMNL2_SVA_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvwp1_toshiba_e
fate-h264-conformance-cvwp1_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/CVWP1_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvwp2_toshiba_e
fate-h264-conformance-cvwp2_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVWP2_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvwp3_toshiba_e
fate-h264-conformance-cvwp3_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVWP3_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-cvwp5_toshiba_e
fate-h264-conformance-cvwp5_toshiba_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/CVWP5_TOSHIBA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-fi1_sony_e
fate-h264-conformance-fi1_sony_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -i $$SAMPLES_PATH/h264-conformance/FI1_Sony_E.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-alphaconformanceg
fate-h264-conformance-frext-alphaconformanceg: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/test8b43.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-bcrm_freh10
fate-h264-conformance-frext-bcrm_freh10: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh10.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-brcm_freh11
fate-h264-conformance-frext-brcm_freh11: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh11.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-brcm_freh3
fate-h264-conformance-frext-brcm_freh3: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh3.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-brcm_freh4
fate-h264-conformance-frext-brcm_freh4: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh4.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-brcm_freh5
fate-h264-conformance-frext-brcm_freh5: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh5.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-brcm_freh8
fate-h264-conformance-frext-brcm_freh8: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh8.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-brcm_freh9
fate-h264-conformance-frext-brcm_freh9: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh9.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-freh12_b
fate-h264-conformance-frext-freh12_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/Freh12_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-freh1_b
fate-h264-conformance-frext-freh1_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/Freh1_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-freh2_b
fate-h264-conformance-frext-freh2_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/Freh2_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-freh6
fate-h264-conformance-frext-freh6: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/freh6.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-freh7_b
fate-h264-conformance-frext-freh7_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/Freh7_B.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext01_jvc_d
fate-h264-conformance-frext-frext01_jvc_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/FREXT01_JVC_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext02_jvc_c
fate-h264-conformance-frext-frext02_jvc_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/FREXT02_JVC_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext1_panasonic_c
fate-h264-conformance-frext-frext1_panasonic_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/FRExt1_Panasonic.avc -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext2_panasonic_b
fate-h264-conformance-frext-frext2_panasonic_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/FRExt2_Panasonic.avc -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext3_panasonic_d
fate-h264-conformance-frext-frext3_panasonic_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/FRExt3_Panasonic.avc -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext4_panasonic_a
fate-h264-conformance-frext-frext4_panasonic_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/FRExt4_Panasonic.avc -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-frext_mmco4_sony_b
fate-h264-conformance-frext-frext_mmco4_sony_b: CMD = $$BUILD_PATH/ffmpeg -strict 1 -i $$SAMPLES_PATH/h264-conformance/FRext/FRExt_MMCO4_Sony_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hcaff1_hhi_b
fate-h264-conformance-frext-hcaff1_hhi_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HCAFF1_HHI.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hcafr1_hhi_c
fate-h264-conformance-frext-hcafr1_hhi_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HCAFR1_HHI.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hcafr2_hhi_a
fate-h264-conformance-frext-hcafr2_hhi_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HCAFR2_HHI.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hcafr3_hhi_a
fate-h264-conformance-frext-hcafr3_hhi_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HCAFR3_HHI.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hcafr4_hhi_a
fate-h264-conformance-frext-hcafr4_hhi_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HCAFR4_HHI.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hcamff1_hhi_b
fate-h264-conformance-frext-hcamff1_hhi_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HCAMFF1_HHI.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpca_brcm_c
fate-h264-conformance-frext-hpca_brcm_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCA_BRCM_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcadq_brcm_b
fate-h264-conformance-frext-hpcadq_brcm_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCADQ_BRCM_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcafl_bcrm_c
fate-h264-conformance-frext-hpcafl_bcrm_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCAFL_BRCM_C.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcaflnl_bcrm_c
fate-h264-conformance-frext-hpcaflnl_bcrm_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCAFLNL_BRCM_C.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcalq_brcm_b
fate-h264-conformance-frext-hpcalq_brcm_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCALQ_BRCM_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcamapalq_bcrm_b
fate-h264-conformance-frext-hpcamapalq_bcrm_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCAMAPALQ_BRCM_B.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcamolq_brcm_b
fate-h264-conformance-frext-hpcamolq_brcm_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCAMOLQ_BRCM_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcanl_brcm_c
fate-h264-conformance-frext-hpcanl_brcm_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCANL_BRCM_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcaq2lq_brcm_b
fate-h264-conformance-frext-hpcaq2lq_brcm_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCAQ2LQ_BRCM_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcv_brcm_a
fate-h264-conformance-frext-hpcv_brcm_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCV_BRCM_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcvfl_bcrm_a
fate-h264-conformance-frext-hpcvfl_bcrm_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCVFL_BRCM_A.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcvflnl_bcrm_a
fate-h264-conformance-frext-hpcvflnl_bcrm_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCVFLNL_BRCM_A.264 -vsync 0 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcvmolq_brcm_b
fate-h264-conformance-frext-hpcvmolq_brcm_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCVMOLQ_BRCM_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-frext-hpcvnl_brcm_a
fate-h264-conformance-frext-hpcvnl_brcm_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/FRext/HPCVNL_BRCM_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-hcbp2_hhi_a
fate-h264-conformance-hcbp2_hhi_a: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/HCBP2_HHI_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-hcmp1_hhi_a
fate-h264-conformance-hcmp1_hhi_a: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/HCMP1_HHI_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-ls_sva_d
fate-h264-conformance-ls_sva_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/LS_SVA_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-midr_mw_d
fate-h264-conformance-midr_mw_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/MIDR_MW_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mps_mw_a
fate-h264-conformance-mps_mw_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/MPS_MW_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr1_bt_a
fate-h264-conformance-mr1_bt_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/MR1_BT_A.h264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr1_mw_a
fate-h264-conformance-mr1_mw_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/MR1_MW_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr2_mw_a
fate-h264-conformance-mr2_mw_a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/MR2_MW_A.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr2_tandberg_e
fate-h264-conformance-mr2_tandberg_e: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR2_TANDBERG_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr3_tandberg_b
fate-h264-conformance-mr3_tandberg_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR3_TANDBERG_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr4_tandberg_c
fate-h264-conformance-mr4_tandberg_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR4_TANDBERG_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr5_tandberg_c
fate-h264-conformance-mr5_tandberg_c: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR5_TANDBERG_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr6_bt_b
fate-h264-conformance-mr6_bt_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR6_BT_B.h264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr7_bt_b
fate-h264-conformance-mr7_bt_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR7_BT_B.h264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr8_bt_b
fate-h264-conformance-mr8_bt_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR8_BT_B.h264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mr9_bt_b
fate-h264-conformance-mr9_bt_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/MR9_BT_B.h264 -f framecrc -
FATE_TESTS += fate-h264-conformance-mv1_brcm_d
fate-h264-conformance-mv1_brcm_d: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/src19td.IBP.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-nl1_sony_d
fate-h264-conformance-nl1_sony_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/NL1_Sony_D.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-nl2_sony_h
fate-h264-conformance-nl2_sony_h: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/NL2_Sony_H.jsv -f framecrc -
FATE_TESTS += fate-h264-conformance-nl3_sva_e
fate-h264-conformance-nl3_sva_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/NL3_SVA_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-nlmq1_jvc_c
fate-h264-conformance-nlmq1_jvc_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/NLMQ1_JVC_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-nlmq2_jvc_c
fate-h264-conformance-nlmq2_jvc_c: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/NLMQ2_JVC_C.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-nrf_mw_e
fate-h264-conformance-nrf_mw_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/NRF_MW_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sharp_mp_field_1_b
fate-h264-conformance-sharp_mp_field_1_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -i $$SAMPLES_PATH/h264-conformance/Sharp_MP_Field_1_B.jvt -f framecrc -
FATE_TESTS += fate-h264-conformance-sharp_mp_field_2_b
fate-h264-conformance-sharp_mp_field_2_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -i $$SAMPLES_PATH/h264-conformance/Sharp_MP_Field_2_B.jvt -f framecrc -
FATE_TESTS += fate-h264-conformance-sharp_mp_field_3_b
fate-h264-conformance-sharp_mp_field_3_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -i $$SAMPLES_PATH/h264-conformance/Sharp_MP_Field_3_B.jvt -f framecrc -
FATE_TESTS += fate-h264-conformance-sharp_mp_paff_1r2
fate-h264-conformance-sharp_mp_paff_1r2: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/Sharp_MP_PAFF_1r2.jvt -f framecrc -
FATE_TESTS += fate-h264-conformance-sharp_mp_paff_2r
fate-h264-conformance-sharp_mp_paff_2r: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/Sharp_MP_PAFF_2.jvt -f framecrc -
FATE_TESTS += fate-h264-conformance-sl1_sva_b
fate-h264-conformance-sl1_sva_b: CMD = $$BUILD_PATH/ffmpeg -vsync 0 -strict 1 -i $$SAMPLES_PATH/h264-conformance/SL1_SVA_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_ba1_b
fate-h264-conformance-sva_ba1_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_BA1_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_ba2_d
fate-h264-conformance-sva_ba2_d: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_BA2_D.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_base_b
fate-h264-conformance-sva_base_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_Base_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_cl1_e
fate-h264-conformance-sva_cl1_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_CL1_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_fm1_e
fate-h264-conformance-sva_fm1_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_FM1_E.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_nl1_b
fate-h264-conformance-sva_nl1_b: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_NL1_B.264 -f framecrc -
FATE_TESTS += fate-h264-conformance-sva_nl2_e
fate-h264-conformance-sva_nl2_e: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/h264-conformance/SVA_NL2_E.264 -f framecrc -
FATE_TESTS += fate-id-cin-video
fate-id-cin-video: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/idcin/idlog-2MB.cin -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-idroq-video-dpcm
fate-idroq-video-dpcm: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/idroq/idlogo.roq -f framecrc -
FATE_TESTS += fate-idroq-video-encode
fate-idroq-video-encode: CMD =  $$BUILD_PATH/ffmpeg -t 0.2 -f image2 -vcodec pgmyuv -i $$SAMPLES_PATH/ffmpeg-synthetic/vsynth1/%02d.pgm -sws_flags +bitexact -padleft 80 -padright 80 -padtop 112 -padbottom 112 -f RoQ - | do_md5sum | cut -c-32
FATE_TESTS += fate-iff-byterun1
fate-iff-byterun1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iff/ASH.LBM -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-iff-fibonacci
fate-iff-fibonacci: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iff/dasboot-in-compressed -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-iff-ilbm
fate-iff-ilbm: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iff/lms-matriks.ilbm -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-iff-pcm
fate-iff-pcm: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iff/Bells -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-indeo2
fate-indeo2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/rt21/VPAR0026.AVI -f framecrc -
FATE_TESTS += fate-indeo3
fate-indeo3: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iv32/cubes.mov -f framecrc -
FATE_TESTS += fate-indeo5
fate-indeo5: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iv50/Educ_Movie_DeadlyForce.avi -an -f framecrc -
FATE_TESTS += fate-interplay-mve-16bit
fate-interplay-mve-16bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/interplay-mve/descent3-level5-16bit-partial.mve -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-interplay-mve-8bit
fate-interplay-mve-8bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/interplay-mve/interplay-logo-2MB.mve -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-iv8-demux
fate-iv8-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/iv8/zzz-partial.mpg -vsync 0 -vcodec copy -f framecrc -
FATE_TESTS += fate-kmvc
fate-kmvc: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/KMVC/LOGO1.AVI -an -t 3 -pix_fmt rgb24  -f framecrc -
FATE_TESTS += fate-lmlm4-demux
fate-lmlm4-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lmlm4/LMLM4_CIFat30fps.divx -t 3 -acodec copy -vcodec copy -f framecrc -
FATE_TESTS += fate-loco-rgb
fate-loco-rgb: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/loco/pig-loco-rgb.avi -f framecrc -
FATE_TESTS += fate-loco-yuy2
fate-loco-yuy2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/loco/pig-loco-0.avi -f framecrc -
FATE_TESTS += fate-lossless-appleaudio
fate-lossless-appleaudio: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/inside.m4a -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-lossless-meridianaudio
fate-lossless-meridianaudio: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/luckynight-partial.mlp -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-lossless-monkeysaudio
fate-lossless-monkeysaudio: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/luckynight-partial.ape -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-lossless-shortenaudio
fate-lossless-shortenaudio: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/luckynight-partial.shn -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-lossless-tta
fate-lossless-tta: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/inside.tta -f crc -
FATE_TESTS += fate-lossless-wavpackaudio
fate-lossless-wavpackaudio: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/luckynight-partial.wv -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-maxis-xa
fate-maxis-xa: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/maxis-xa/SC2KBUG.XA -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-mimic
fate-mimic: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/mimic/mimic2-womanloveffmpeg.cam -vsync 0 -f framecrc -
FATE_TESTS += fate-motionpixels
fate-motionpixels: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/motion-pixels/INTRO-partial.MVI -an -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-mpc7-demux
fate-mpc7-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/musepack/inside-mp7.mpc -acodec copy -f crc -
FATE_TESTS += fate-mpc8-demux
fate-mpc8-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/musepack/inside-mp8.mpc -acodec copy -f crc -
FATE_TESTS += fate-mpeg4-als-conformance-00
fate-mpeg4-als-conformance-00: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/als_00_2ch48k16b.mp4 -f crc -
FATE_TESTS += fate-mpeg4-als-conformance-01
fate-mpeg4-als-conformance-01: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/als_01_2ch48k16b.mp4 -f crc -
FATE_TESTS += fate-mpeg4-als-conformance-02
fate-mpeg4-als-conformance-02: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/als_02_2ch48k16b.mp4 -f crc -
FATE_TESTS += fate-mpeg4-als-conformance-03
fate-mpeg4-als-conformance-03: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/als_03_2ch48k16b.mp4 -f crc -
FATE_TESTS += fate-mpeg4-als-conformance-04
fate-mpeg4-als-conformance-04: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/als_04_2ch48k16b.mp4 -f crc -
FATE_TESTS += fate-mpeg4-als-conformance-05
fate-mpeg4-als-conformance-05: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lossless-audio/als_05_2ch48k16b.mp4 -f crc -
FATE_TESTS += fate-msrle-8bit
fate-msrle-8bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/msrle/Search-RLE.avi -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-msvideo1-16bit
fate-msvideo1-16bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cram/clock-cram16.avi -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-msvideo1-8bit
fate-msvideo1-8bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/cram/skating.avi -t 1 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-mszh
fate-mszh: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lcl/mszh-1frame.avi -f framecrc -
FATE_TESTS += fate-mtv
fate-mtv: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/mtv/comedian_auto-partial.mtv -acodec copy -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-mxf-demux
fate-mxf-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/mxf/C0023S01.mxf -acodec copy -vcodec copy -f framecrc -
FATE_TESTS += fate-nc-demux
fate-nc-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/nc-camera/nc-sample-partial -vcodec copy -f framecrc -
FATE_TESTS += fate-nsv-demux
fate-nsv-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/nsv/witchblade-51kbps.nsv -t 6 -vcodec copy -acodec copy -f framecrc -
FATE_TESTS += fate-nuv
fate-nuv: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/nuv/Today.nuv -f framecrc -
FATE_TESTS += fate-oma-demux
fate-oma-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/oma/01-Untitled-partial.oma -acodec copy -f crc -
FATE_TESTS += fate-pcm_dvd
fate-pcm_dvd: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/pcm-dvd/coolitnow-partial.vob -vn -f framecrc -
FATE_TESTS += fate-psx-str
fate-psx-str: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/psx-str/descent-partial.str -f framecrc -
FATE_TESTS += fate-ptx
fate-ptx: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ptx/_113kw_pic.ptx -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-pva-demux
fate-pva-demux: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/pva/PVA_test-partial.pva -t 0.6 -acodec copy -f framecrc -
FATE_TESTS += fate-qcp-demux
fate-qcp-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qcp/0036580847.QCP -acodec copy -f crc -
FATE_TESTS += fate-qpeg
fate-qpeg: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qpeg/Clock.avi -an -pix_fmt rgb24  -f framecrc -
FATE_TESTS += fate-qt-alaw-mono
fate-qt-alaw-mono: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-1-16-B-alaw.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-alaw-stereo
fate-qt-alaw-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-B-alaw.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-ima4-mono
fate-qt-ima4-mono: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-1-16-B-ima4.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-ima4-stereo
fate-qt-ima4-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-B-ima4.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-mac3-mono
fate-qt-mac3-mono: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-1-8-MAC3.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-mac3-stereo
fate-qt-mac3-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-8-MAC3.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-mac6-mono
fate-qt-mac6-mono: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-1-8-MAC6.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-mac6-stereo
fate-qt-mac6-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-8-MAC6.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-msadpcm-stereo
fate-qt-msadpcm-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-L-ms02.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-msimaadpcm-stereo
fate-qt-msimaadpcm-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-L-ms11.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-rawpcm-16bit-stereo-signed-be
fate-qt-rawpcm-16bit-stereo-signed-be: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-B-twos.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-rawpcm-16bit-stereo-signed-le
fate-qt-rawpcm-16bit-stereo-signed-le: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-L-sowt.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-rawpcm-8bit-mono-unsigned
fate-qt-rawpcm-8bit-mono-unsigned: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-1-8-raw.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-rawpcm-8bit-stereo-unsigned
fate-qt-rawpcm-8bit-stereo-unsigned: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-8-raw.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-ulaw-mono
fate-qt-ulaw-mono: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-1-16-B-ulaw.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qt-ulaw-stereo
fate-qt-ulaw-stereo: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qt-surge-suite/surge-2-16-B-ulaw.mov -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-qtrle-16bit
fate-qtrle-16bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/mr-cork-rle.mov -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-qtrle-1bit
fate-qtrle-1bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/Animation-Monochrome.mov -f framecrc -
FATE_TESTS += fate-qtrle-24bit
fate-qtrle-24bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/aletrek-rle.mov -vsync 0 -f framecrc -
FATE_TESTS += fate-qtrle-2bit
fate-qtrle-2bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/Animation-4Greys.mov -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-qtrle-32bit
fate-qtrle-32bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/ultra_demo_720_480_32bpp_rle.mov -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-qtrle-4bit
fate-qtrle-4bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/Animation-16Greys.mov -pix_fmt rgb24 -an -f framecrc -
FATE_TESTS += fate-qtrle-8bit
fate-qtrle-8bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/qtrle/criticalpath-credits.mov -vsync 0 -pix_fmt rgb24 -an -f framecrc -
FATE_TESTS += fate-quickdraw
fate-quickdraw: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/quickdraw/Airplane.mov -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-real-14_4
fate-real-14_4: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/real/ra3_in_rm_file.rm -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-real-rv40
fate-real-rv40: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/real/spygames-2MB.rmvb -t 10 -an -f framecrc -
FATE_TESTS += fate-redcode-demux
fate-redcode-demux: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/r3d/4MB-sample.r3d -vcodec copy -acodec copy -f framecrc -
FATE_TESTS += fate-rl2
fate-rl2: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/rl2/Z4915300.RL2 -pix_fmt rgb24 -an -vsync 0 -f framecrc -
FATE_TESTS += fate-rpza
fate-rpza: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/rpza/rpza2.mov -t 2 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-sierra-audio
fate-sierra-audio: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sol/lsl7sample.sol -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-sierra-vmd
fate-sierra-vmd: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vmd/12.vmd -vsync 0 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-siff
fate-siff: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/SIFF/INTRO_B.VB -t 3 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-smacker
fate-smacker: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/smacker/wetlogo.smk -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-smc
fate-smc: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/smc/cass_schi.qt -vsync 0 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-sp5x
fate-sp5x: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/sp5x/sp5x_problem.avi -f framecrc -
FATE_TESTS += fate-sunraster-1bit-raw
fate-sunraster-1bit-raw: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sunraster/lena-1bit-raw.sun -f framecrc -
FATE_TESTS += fate-sunraster-1bit-rle
fate-sunraster-1bit-rle: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sunraster/lena-1bit-rle.sun -f framecrc -
FATE_TESTS += fate-sunraster-24bit-raw
fate-sunraster-24bit-raw: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sunraster/lena-24bit-raw.sun -f framecrc -
FATE_TESTS += fate-sunraster-24bit-rle
fate-sunraster-24bit-rle: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sunraster/lena-24bit-rle.sun -f framecrc -
FATE_TESTS += fate-sunraster-8bit-raw
fate-sunraster-8bit-raw: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sunraster/lena-8bit-raw.sun -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-sunraster-8bit-rle
fate-sunraster-8bit-rle: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/sunraster/lena-8bit-rle.sun -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-svq1
fate-svq1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/svq1/marymary-shackles.mov -an -t 10 -f framecrc -
FATE_TESTS += fate-svq3
fate-svq3: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/svq3/Vertical400kbit.sorenson3.mov -t 6 -an -f framecrc -
FATE_TESTS += fate-thp-mjpeg-adpcm
fate-thp-mjpeg-adpcm: CMD = $$BUILD_PATH/ffmpeg -idct simple -i $$SAMPLES_PATH/thp/pikmin2-opening1-partial.thp -f framecrc -
FATE_TESTS += fate-tiertex-seq
fate-tiertex-seq: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/tiertex-seq/Gameover.seq -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-tmv
fate-tmv: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/tmv/pop-partial.tmv -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-tscc-15bit
fate-tscc-15bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/tscc/oneminute.avi -t 15 -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-tscc-32bit
fate-tscc-32bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/tscc/2004-12-17-uebung9-partial.avi -pix_fmt rgb24 -an -f framecrc -
FATE_TESTS += fate-ulti
fate-ulti: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/ulti/hit12w.avi -an -f framecrc -
FATE_TESTS += fate-v210
fate-v210: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/v210/v210_720p-partial.avi -pix_fmt yuv422p16be -an -f framecrc -
FATE_TESTS += fate-vc1
fate-vc1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vc1/SA00040.vc1 -f framecrc -
FATE_TESTS += fate-vcr1
fate-vcr1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vcr1/VCR1test.avi -an -f framecrc -
FATE_TESTS += fate-video-xl
fate-video-xl: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vixl/pig-vixl.avi -f framecrc -
FATE_TESTS += fate-vmnc-16bit
fate-vmnc-16bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/VMnc/test.avi -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-vmnc-32bit
fate-vmnc-32bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/VMnc/VS2k5DebugDemo-01-partial.avi -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-vp5
fate-vp5: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vp5/potter512-400-partial.avi -an -f framecrc -
FATE_TESTS += fate-vp6a
fate-vp6a: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/flash-vp6/300x180-Scr-f8-056alpha.flv -f framecrc -
FATE_TESTS += fate-vp6f
fate-vp6f: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/flash-vp6/clip1024.flv -f framecrc -
FATE_TESTS += fate-vqa-cc
fate-vqa-cc: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vqa/cc-demo1-partial.vqa -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-vqf-demux
fate-vqf-demux: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/vqf/achterba.vqf -acodec copy -f framecrc - | do_md5sum | cut -c-32
FATE_TESTS += fate-w64
fate-w64: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/w64/w64-pcm16.w64 -f crc -
FATE_TESTS += fate-wc3movie-xan
fate-wc3movie-xan: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/wc3movie/SC_32-part.MVE -pix_fmt rgb24 -f framecrc -
FATE_TESTS += fate-westwood-aud
fate-westwood-aud: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/westwood-aud/excellent.aud -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-wnv1
fate-wnv1: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/wnv1/wnv1-codec.avi -an -f framecrc -
FATE_TESTS += fate-xan-dpcm
fate-xan-dpcm: CMD =  $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/wc4-xan/wc4_2.avi -vn -f s16le - | do_md5sum | cut -c-32
FATE_TESTS += fate-zlib
fate-zlib: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/lcl/zlib-1frame.avi -f framecrc -
FATE_TESTS += fate-zmbv-15bit
fate-zmbv-15bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/zmbv/zmbv_15bit.avi -pix_fmt rgb24 -t 25 -f framecrc -
FATE_TESTS += fate-zmbv-16bit
fate-zmbv-16bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/zmbv/zmbv_16bit.avi -pix_fmt rgb24 -t 25 -f framecrc -
FATE_TESTS += fate-zmbv-32bit
fate-zmbv-32bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/zmbv/zmbv_32bit.avi -pix_fmt rgb24 -t 25 -f framecrc -
FATE_TESTS += fate-zmbv-8bit
fate-zmbv-8bit: CMD = $$BUILD_PATH/ffmpeg -i $$SAMPLES_PATH/zmbv/wc2_001-partial.avi -an -pix_fmt rgb24 -f framecrc -
