OBJS      += x86/audio_convert_init.o                                   \
             x86/audio_mix_init.o                                       \

YASM-OBJS += x86/audio_convert.o                                        \
             x86/audio_mix.o                                            \
