OBJS      += x86/audio_convert_init.o                                   \
             x86/audio_mix_init.o                                       \
             x86/dither_init.o                                          \

OBJS-$(CONFIG_XMM_CLOBBER_TEST) += x86/w64xmmtest.o

X86ASM-OBJS += x86/audio_convert.o                                      \
             x86/audio_mix.o                                            \
             x86/dither.o                                               \
