OBJS        += aarch64/swscale.o                \
               aarch64/swscale_unscaled.o       \

NEON-OBJS   += aarch64/hscale.o                 \
               aarch64/output.o                 \
               aarch64/yuv2rgb_neon.o           \
