OBJS += arm/cpu.o                                                       \
        arm/float_dsp_init_arm.o                                        \

ARMV6-OBJS-$(CONFIG_PIXELUTILS) += arm/pixelutils_armv6.o

VFP-OBJS += arm/float_dsp_init_vfp.o                                    \
            arm/float_dsp_vfp.o                                         \

NEON-OBJS += arm/float_dsp_init_neon.o                                  \
             arm/float_dsp_neon.o                                       \
