MMI-OBJS += mips/dsputil_mmi.o                                          \
            mips/idct_mmi.o                                             \

MMI-OBJS-$(CONFIG_MPEGVIDEO)            += mips/mpegvideo_mmi.o
