include $(SUBDIR)../config.mak

NAME = swresample
FFLIBS = avutil

HEADERS = swresample.h

OBJS = swresample.o audioconvert.o resample2.o rematrix.o

TESTPROGS = swresample_test

include $(SUBDIR)../subdir.mak
