YASM-OBJS                       += x86/swresample_x86.o\
                                   x86/audio_convert.o\
                                   x86/rematrix.o\

OBJS-$(CONFIG_XMM_CLOBBER_TEST) += x86/w64xmmtest.o
