OBJS += riscv/rgb2rgb.o \
        riscv/swscale.o
RV-OBJS += riscv/rgb2rgb_rvb.o
RVV-OBJS += riscv/input_rvv.o \
            riscv/range_rvv.o \
            riscv/rgb2rgb_rvv.o

SHLIBOBJS += riscv/cpu_common.o
