OBJS-$(CONFIG_AFIR_FILTER)                   += riscv/af_afir_init.o
RVV-OBJS-$(CONFIG_AFIR_FILTER)               += riscv/af_afir_rvv.o
OBJS-$(CONFIG_BLACKDETECT_FILTER) += riscv/vf_blackdetect_init.o
RVV-OBJS-$(CONFIG_BLACKDETECT_FILTER) += riscv/vf_blackdetect_rvv.o

SHLIBOBJS += riscv/cpu_common.o
