OBJS += sh4/dsputil_align.o                                             \
        sh4/dsputil_sh4.o                                               \
        sh4/idct_sh4.o                                                  \

OBJS-$(CONFIG_H264CHROMA)               += sh4/h264chroma_init.o        \
