OBJS += sh4/dsputil_align.o                                             \
        sh4/dsputil_sh4.o                                               \
        sh4/idct_sh4.o                                                  \
