OBJS +=     riscv/float_dsp_init.o \
            riscv/fixed_dsp_init.o \
            riscv/lls_init.o \
            riscv/cpu.o \
            riscv/cpu_common.o
RVV-OBJS += riscv/float_dsp_rvv.o \
            riscv/fixed_dsp_rvv.o \
            riscv/lls_rvv.o
