include $(SUBDIR)../config.mak

NAME = avcore
FFLIBS = avutil

HEADERS = avcore.h                                                      \
          parseutils.h                                                  \

OBJS = parseutils.o                                                     \
       utils.o                                                          \

include $(SUBDIR)../subdir.mak
