include $(SUBDIR)../config.mak

NAME = avcore
FFLIBS = avutil

HEADERS = \
          audioconvert.h                                                \
          avcore.h                                                      \
          imgutils.h                                                    \
          parseutils.h                                                  \
          samplefmt.h                                                   \

OBJS = \
       audioconvert.o                                                   \
       imgutils.o                                                       \
       parseutils.o                                                     \
       samplefmt.o                                                      \
       utils.o                                                          \

include $(SUBDIR)../subdir.mak
