OBJS-$(CONFIG_SWSCALE)      += loongarch/swscale_init_loongarch.o
LASX-OBJS-$(CONFIG_SWSCALE) += loongarch/swscale_lasx.o \
                               loongarch/input_lasx.o   \
                               loongarch/yuv2rgb_lasx.o \
                               loongarch/rgb2rgb_lasx.o \
                               loongarch/output_lasx.o
LSX-OBJS-$(CONFIG_SWSCALE)  += loongarch/swscale.o \
                               loongarch/swscale_unscaled.o \
                               loongarch/hscale_fast_bilinear_lsx.o \
                               loongarch/swscale_lsx.o \
                               loongarch/input.o   \
                               loongarch/output.o  \
                               loongarch/output_lsx.o  \
                               loongarch/input_lsx.o   \
                               loongarch/yuv2rgb_lsx.o
