OBJS += alpha/dsputil_alpha.o                                           \
        alpha/dsputil_alpha_asm.o                                       \
        alpha/motion_est_alpha.o                                        \
        alpha/motion_est_mvi_asm.o                                      \
        alpha/simple_idct_alpha.o                                       \

OBJS-$(CONFIG_MPEGVIDEO)                += alpha/mpegvideo_alpha.o
