OBJS += x86/cpu.o                                                       \
        x86/float_dsp_init.o                                            \

YASM-OBJS += x86/float_dsp.o                                            \
