OBJS += x86/cpu.o                                                       \
        x86/float_dsp_init.o                                            \
        x86/lls_init.o                                                  \

YASM-OBJS += x86/cpuid.o                                                \
             x86/emms.o                                                 \
             x86/float_dsp.o                                            \
             x86/lls.o                                                  \
