#!/bin/sh

set -e

if test "bisect" = "`basename $0`" ; then
    echo WARNING, trying to execute tools/bisect directly this cannot work as
    echo the script itself would not be available in older checkouts
    echo please use tools/ffbisect
    git show master:tools/bisect > tools/ffbisect
    chmod u+x tools/ffbisect
    exit 1
fi

if ! git show master:tools/bisect | diff - tools/ffbisect > /dev/null ; then
    echo updating tools/ffbisect script to HEAD.
    git show master:tools/bisect > tools/ffbisect
    chmod u+x tools/ffbisect
    tools/ffbisect $*
    exit 0
fi

case "$1" in
    need)
        case $2 in
            ffmpeg|ffplay|ffprobe|ffserver)
                echo $2.c >> tools/bisect.need
            ;;
        esac
    ;;
    start|reset)
        echo . > tools/bisect.need
        git bisect $*
    ;;
    skip)
        git bisect $*
    ;;
    good|bad)
        git bisect $*

        until ls `cat tools/bisect.need` > /dev/null 2> /dev/null; do
            git bisect skip || break
        done
    ;;
esac
