#!/bin/sh
sed '/^+[^+]/!s/	/TaBBaT/g' |\
 expand -t $(seq -s , 9 8 200) |\
 sed 's/TaBBaT/	/g' |\
 sed '/^+[^+]/s/ * $//' |\
 tr -d '\015' |\
 tr '\n' '°' |\
 sed 's/\(@@[^@]*@@°[^@]*\)/\n\1/g' |\
 egrep -v '@@[^@]*@@°(( [^°]*°)|([+-][[:space:]]*°)|(-[[:space:]]*([^°]*)°\+[[:space:]]*\5°))*$' |\
 tr -d '\n' |\
 tr '°' '\n'
