OBJS-$(CONFIG_H264CHROMA)             += loongarch/h264chroma_init_loongarch.o
OBJS-$(CONFIG_H264QPEL)               += loongarch/h264qpel_init_loongarch.o
OBJS-$(CONFIG_H264DSP)                += loongarch/h264dsp_init_loongarch.o
LASX-OBJS-$(CONFIG_H264CHROMA)        += loongarch/h264chroma_lasx.o
LASX-OBJS-$(CONFIG_H264QPEL)          += loongarch/h264qpel_lasx.o
LASX-OBJS-$(CONFIG_H264DSP)           += loongarch/h264dsp_lasx.o \
                                         loongarch/h264idct_lasx.o
