FATE_CHECKASM = fate-checkasm-aacencdsp                                 \
                fate-checkasm-aacpsdsp                                  \
                fate-checkasm-ac3dsp                                    \
                fate-checkasm-af_afir                                   \
                fate-checkasm-alacdsp                                   \
                fate-checkasm-audiodsp                                  \
                fate-checkasm-av_tx                                     \
                fate-checkasm-blockdsp                                  \
                fate-checkasm-bswapdsp                                  \
                fate-checkasm-exrdsp                                    \
                fate-checkasm-fdctdsp                                   \
                fate-checkasm-fixed_dsp                                 \
                fate-checkasm-flacdsp                                   \
                fate-checkasm-float_dsp                                 \
                fate-checkasm-fmtconvert                                \
                fate-checkasm-g722dsp                                   \
                fate-checkasm-h263dsp                                   \
                fate-checkasm-h264chroma                                \
                fate-checkasm-h264dsp                                   \
                fate-checkasm-h264pred                                  \
                fate-checkasm-h264qpel                                  \
                fate-checkasm-hevc_add_res                              \
                fate-checkasm-hevc_deblock                              \
                fate-checkasm-hevc_idct                                 \
                fate-checkasm-hevc_pel                                  \
                fate-checkasm-hevc_sao                                  \
                fate-checkasm-huffyuvdsp                                \
                fate-checkasm-idctdsp                                   \
                fate-checkasm-jpeg2000dsp                               \
                fate-checkasm-llauddsp                                  \
                fate-checkasm-lls                                       \
                fate-checkasm-llviddsp                                  \
                fate-checkasm-llviddspenc                               \
                fate-checkasm-lpc                                       \
                fate-checkasm-motion                                    \
                fate-checkasm-mpegvideoencdsp                           \
                fate-checkasm-opusdsp                                   \
                fate-checkasm-pixblockdsp                               \
                fate-checkasm-sbrdsp                                    \
                fate-checkasm-rv34dsp                                   \
                fate-checkasm-rv40dsp                                   \
                fate-checkasm-svq1enc                                   \
                fate-checkasm-synth_filter                              \
                fate-checkasm-sw_gbrp                                   \
                fate-checkasm-sw_range_convert                          \
                fate-checkasm-sw_rgb                                    \
                fate-checkasm-sw_scale                                  \
                fate-checkasm-sw_yuv2rgb                                \
                fate-checkasm-sw_yuv2yuv                                \
                fate-checkasm-takdsp                                    \
                fate-checkasm-utvideodsp                                \
                fate-checkasm-v210dec                                   \
                fate-checkasm-v210enc                                   \
                fate-checkasm-vc1dsp                                    \
                fate-checkasm-vf_blend                                  \
                fate-checkasm-vf_bwdif                                  \
                fate-checkasm-vf_colorspace                             \
                fate-checkasm-vf_eq                                     \
                fate-checkasm-vf_gblur                                  \
                fate-checkasm-vf_hflip                                  \
                fate-checkasm-vf_nlmeans                                \
                fate-checkasm-vf_threshold                              \
                fate-checkasm-vf_sobel                                  \
                fate-checkasm-videodsp                                  \
                fate-checkasm-vorbisdsp                                 \
                fate-checkasm-vp8dsp                                    \
                fate-checkasm-vp9dsp                                    \
                fate-checkasm-vvc_alf                                   \
                fate-checkasm-vvc_mc                                    \

$(FATE_CHECKASM): tests/checkasm/checkasm$(EXESUF)
$(FATE_CHECKASM): CMD = run tests/checkasm/checkasm$(EXESUF) --test=$(@:fate-checkasm-%=%)
$(FATE_CHECKASM): CMP = null

FATE += $(FATE_CHECKASM)
fate-checkasm: $(FATE_CHECKASM)
