#!/bin/sh

# Copyright © 2026, Martin Storsjo
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

LSCPU="$1"

if [ -z "$LSCPU" ]; then
    echo $0 lscpu-binary
    exit 1
fi

make_symbol() {
    echo "$1" | sed 's/[^A-Za-z_]/_/g' | tr A-Z a-z
}

echo "/* Autogenerated with gen-arm-core-table.sh */"
echo "/* clang-format off */"
"$LSCPU" --arm-id | tail -n +2 | while read line; do
    id=$(echo $line | cut -f 1 -d " ")
    name=$(echo $line | cut -f 2- -d " ")
    echo "static const struct arm_core cores_$(make_symbol "$name")[] = {"
    "$LSCPU" --arm-id=$id | tail -n +2 | while read line; do
        core_id=$(echo $line | cut -f 1 -d " ")
        core_name=$(echo $line | cut -f 2- -d " ")
        echo "    { $core_id, \"$core_name\" },"
    done
    echo "    { 0,     NULL },"
    echo "};"
    echo ""
done

echo "static const struct arm_implementer arm_implementers[] = {"
"$LSCPU" --arm-id | tail -n +2 | while read line; do
    id=$(echo $line | cut -f 1 -d " ")
    name=$(echo $line | cut -f 2- -d " ")
    echo "    { $id, cores_$(make_symbol "$name"), \"$name\" },"
done
echo "    { 0,    NULL, NULL },"
echo "};"
